# whitelist
branches:
  only:
    - master
    - ci
language: node_js
node_js:
- '0.12'
- '0.11'
env: BROWSERS=firefox E2E_BROWSERS=Firefox
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- npm run update-webdriver
- gem install sass

before_script:
- 'npm -g install bower gulp'
- 'npm install'
- 'bower install'

script:
- script.sh