# whitelist
branches:
  only:
    - master
    - ci
language: node_js

node_js:
- '0.12'
- '0.11'

env: BROWSERS=google-chrome E2E_BROWSERS=google-chrome

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- gem install sass

before_script:
- 'npm -g install bower gulp'
- 'npm install'
- 'bower install'
- 'chmod a+x script.sh'

script: ./script.sh