language: node_js
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- gem install sass

node_js:
- '4.1'
- '4.0'

before_script:
- 'npm -g install bower gulp'
- 'npm install'
- 'bower install'

script: 
- gulp initialize
- gulp script
- gulp style