# whitelist
branches:
  only:
    - master
    - ci

language: node_js

node_js:
- '0.12'
- '0.11'

env: 
	matrix:
    - MODE='check'
    - BROWSER=Chrome-stable ARGS='-x -b Chrome -u'
    - BROWSER=Chrome-beta ARGS='-x -b Chrome -u'
    - BROWSER=Chrome-unstable ARGS='-x -b Chrome -u'
    - BROWSER=Firefox-stable ARGS='-x -b Firefox -u'
    - BROWSER=Firefox-beta ARGS='-x -b Firefox -u'
    - BROWSER=Firefox-aurora ARGS='-x -b Firefox -u'

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- gem install sass

before_script:
- 'npm -g install bower gulp'
- 'npm install'
- 'bower install'
- 'chmod a+x script.sh'

script: ./script.sh