# whitelist
branches:
  only:
    - master
    - ci
language: node_js
node_js:
- '0.12'
- '0.11'

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- chmod a+x script.sh
- gem install sass

before_script:
- 'npm -g install bower gulp'
- 'npm install'
- 'bower install'

script:
- npm run update-webdriver
- gulp compile
- http-server ./www -p 3030 & WEBSERVER_PID=$!
- npm run unit-firefox
- npm run protractor-firefox