# whitelist
# cd /home/travis/build/SixthFloor/FECS-Web
branches:
  only:
    - master
    - ci
language: node_js
node_js:
- '0.12'
- '0.11'

before_install:
- sudo apt-get install -qq sshpass
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# - chmod a+x script.sh
- gem install sass

before_script:
- 'npm -g install bower gulp'
- 'npm install'
- 'bower install'

script:
- npm run update-webdriver
- gulp compile
- http-server ./www -p 3030 & WEBSERVER_PID=$!
<<<<<<< HEAD
- npm run unit-firefox
- npm run protractor-firefox

after_script:
- echo "Hello it can use!!"
=======
# - npm run unit-firefox
- npm run protractor-firefox

after_script:
- mv ./reports/ test_"${REPORT_DATE}"_"(${NUMBER_FILE})"/
- sshpass -p jl scp -r test_"${REPORT_DATE}"_"(${NUMBER_FILE})"/ jl@128.199.133.224:/home/jl/Test_reports/feature-tests/
>>>>>>> testing
